# Discord link GitHub issue form
# 
# This file needs to reside in the ".github/ISSUE_TEMPLATE/" folder.

name: Discord
description: Join our Discord server
title: "Discord"
body:
  - type: markdown
    attributes:
      value: |
        For the best support experience, and to connect directly with the DCC-EX team, join our `Discord server <https://discord.gg/y2sB4Fp>`!